version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - PORT=6060
    ports:
      - "8080:6060"
    networks:
      - ascii-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - ascii-net

networks:
  ascii-net:
